language: bash

sudo: required

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

services:
 - docker

script:
 - find . -iname "*.sh" -exec shellcheck "{}" \;
 - ./docker-build.sh -b arm -d pi -v 2.$(git rev-list HEAD --count)

matrix:
  fast_finish: true
